"""Create schema

Revision ID: 288d27806da0
Revises: 4a987664ecb4
Create Date: 2016-11-11 22:33:14.141890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '288d27806da0'
down_revision = '4a987664ecb4'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_key', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.CheckConstraint(u"url ~* '^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$'", name='c_check_feed_url'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_key', name='c_unique_feed_refKey')
    )
    op.create_index(op.f('ix_feed_is_enabled'), 'feed', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feed_ref_key'), 'feed', ['ref_key'], unique=False)
    op.create_table('feed_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url_regexp', sa.String(length=255), nullable=False),
    sa.Column('content_regexp', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ref_key', name='c_unique_feedType_refKey')
    )
    op.create_index(op.f('ix_feed_type_is_enabled'), 'feed_type', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feed_type_ref_key'), 'feed_type', ['ref_key'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.CheckConstraint(u"email ~* '^[A-Za-z0-9._%%-]+@[A-Za-z0-9.-]+[.][A-Za-z]+$'", name='c_check_user_email'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='c_unique_user_username')
    )
    op.create_index(op.f('ix_user_is_enabled'), 'user', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=False)
    op.create_table('feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('feed_type', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_reposted', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.CheckConstraint(u"url ~* '^(https?:\\/\\/)?([\\da-z\\.-]+)\\.([a-z\\.]{2,6})([\\/\\w \\.-]*)*\\/?$'", name='c_check_feedItem_url'),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name='fk_feedItem_parent_feedId'),
    sa.ForeignKeyConstraint(['feed_type'], ['feed_type.id'], name='fk_feedItem_parent_feedType'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index(op.f('ix_feed_item_is_approved'), 'feed_item', ['is_approved'], unique=False)
    op.create_index(op.f('ix_feed_item_is_enabled'), 'feed_item', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feed_item_is_reposted'), 'feed_item', ['is_reposted'], unique=False)
    op.create_index(op.f('ix_feed_item_is_sent'), 'feed_item', ['is_sent'], unique=False)
    op.create_index(op.f('ix_feed_item_is_viewed'), 'feed_item', ['is_viewed'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_item_is_viewed'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_is_sent'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_is_reposted'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_is_enabled'), table_name='feed_item')
    op.drop_index(op.f('ix_feed_item_is_approved'), table_name='feed_item')
    op.drop_table('feed_item')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_is_enabled'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_feed_type_ref_key'), table_name='feed_type')
    op.drop_index(op.f('ix_feed_type_is_enabled'), table_name='feed_type')
    op.drop_table('feed_type')
    op.drop_index(op.f('ix_feed_ref_key'), table_name='feed')
    op.drop_index(op.f('ix_feed_is_enabled'), table_name='feed')
    op.drop_table('feed')
    ### end Alembic commands ###
