"""Create schema

Revision ID: 5ddd682ae4d0
Revises: 4a987664ecb4
Create Date: 2016-11-11 17:14:40.720292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddd682ae4d0'
down_revision = '4a987664ecb4'
branch_labels = None
depends_on = None

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ref_key', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feed_is_enabled'), 'feed', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_feed_ref_key'), 'feed', ['ref_key'], unique=True)
    op.create_table('feed_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('url_regexp', sa.String(length=255), nullable=False),
    sa.Column('content_regexp', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('feed_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=True),
    sa.Column('feed_type', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('tags', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_reposted', sa.Boolean(), nullable=False),
    sa.Column('is_sent', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feed.id'], name='fk_feedItem_parent_feedId'),
    sa.ForeignKeyConstraint(['feed_type'], ['feed_type.id'], name='fk_feedItem_parent_feedType'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_item')
    op.drop_table('user')
    op.drop_table('feed_type')
    op.drop_index(op.f('ix_feed_ref_key'), table_name='feed')
    op.drop_index(op.f('ix_feed_is_enabled'), table_name='feed')
    op.drop_table('feed')
    ### end Alembic commands ###
